Repository eeoooue/networked-cube, pull requests merged in 2025-05, with the labels that each got.

#55 Visual Polish
  Solution/FaceViewer/MainWindow.xaml
  Solution/FaceViewer/ViewModels/FaceViewModel.cs
  Solution/FaceViewer/Views/FaceView.xaml
Labels: Front End, WPF

#56 Solution Cleaning & Repository Presentation
  README.md
  Solution/AdminPanel/MainWindow.xaml
  Solution/CubeRotator/App.xaml
  Solution/CubeRotator/App.xaml.cs
  Solution/CubeRotator/AssemblyInfo.cs
  Solution/CubeRotator/CubeRotator.csproj
  Solution/CubeRotator/MainWindow.xaml
  Solution/CubeRotator/MainWindow.xaml.cs
  Solution/CubeViewFacade/CubeViewFacade.csproj
  Solution/CubeViewFacade/CubeViewingHost.cs
  Solution/CubeViewFacade/Program.cs
  Solution/CubeVisualizer/CubeGame.cs
  Solution/DevConsole/DevConsole.csproj
  Solution/DevConsole/Program.cs
  Solution/FaceViewerCLI/Program.cs
  Solution/LibCubeIntegration/GetCubeStrategies/GetCubeViaAPIStrategy.cs
  Solution/LibCubeIntegration/GetCubeStrategies/GetCubeViaSocketStrategy.cs
  Solution/LibCubeIntegration/NetworkingConfiguration.cs
  Solution/LibCubeIntegration/PerformMoveStrategies/MoveViaAPIStrategy.cs
  Solution/LibCubeIntegration/PerformMoveStrategies/MoveViaSocketStrategy.cs
  Solution/LibCubeIntegration/Services/CubeServiceFacade.cs
  Solution/LibCubeIntegration/StrategyVendor.cs
  Solution/Solution.sln
  misc/example-screenshot.png
  misc/netcube-system-design.png
Labels: documentation, Networking, Library / CLI

#61 Add CubeStatePublisher project, which updates frontends about CubeState changes
  README.md
  Solution/CubeStatePublisher/CubeHub.cs
  Solution/CubeStatePublisher/CubeStatePublisher.csproj
  Solution/CubeStatePublisher/Program.cs
  Solution/CubeStatePublisher/Properties/launchSettings.json
  Solution/CubeStatePublisher/PublishCubeService.cs
  Solution/CubeVisualizer/CubeGame.cs
  Solution/CubeVisualizer/CubeVisualizer.csproj
  Solution/FaceViewer/FaceViewer.csproj
  Solution/FaceViewer/ViewModels/FaceViewModel.cs
  Solution/FaceViewer/ViewModels/MainViewModel.cs
  Solution/LibCubeIntegration/JsonFriendlyCubeState.cs
  Solution/LibCubeIntegration/LibCubeIntegration.csproj
  Solution/LibCubeIntegration/NetworkingConfiguration.cs
  Solution/LibCubeIntegration/Services/CubePublisherService.cs
  Solution/Solution.sln
Labels: Networking, Library / CLI

#65 Add CubeProxy API Project
  README.md
  Solution/CubeManipulator/CubeManipulatorViewModel.cs
  Solution/CubeProxy/Controllers/CubeController.cs
  Solution/CubeProxy/CubeProxy.csproj
  Solution/CubeProxy/CubeProxy.http
  Solution/CubeProxy/Program.cs
  Solution/CubeProxy/Properties/launchSettings.json
  Solution/CubeProxy/appsettings.Development.json
  Solution/CubeProxy/appsettings.json
  Solution/CubeStatePublisher/PublishCubeService.cs
  Solution/LibCubeIntegration/NetworkingConfiguration.cs
  Solution/Solution.sln
Labels: Networking, Web API

#66 CubeService API: /ApplyShuffle Implementation
  Solution/CubeService/Controllers/CubeController.cs
Labels: Back End, Web API

#67 Implemented a CubeResetStrategy
  Solution/AdminPanel/AdminPanel.csproj
  Solution/AdminPanel/MainWindow.xaml
  Solution/AdminPanel/MainWindow.xaml.cs
  Solution/CubeProxy/Controllers/CubeController.cs
  Solution/LibCubeIntegration/ResetCubeStrategies/IResetCubeStrategy.cs
  Solution/LibCubeIntegration/ResetCubeStrategies/ResetCubeViaAPIStrategy.cs
Labels: Networking, Library / CLI

#68 Implemented a ShuffleCubeStrategy
  Solution/AdminPanel/MainWindow.xaml
  Solution/AdminPanel/MainWindow.xaml.cs
  Solution/CubeProxy/Controllers/CubeController.cs
  Solution/LibCubeIntegration/ShuffleCubeStrategies/IShuffleCubeStrategy.cs
  Solution/LibCubeIntegration/ShuffleCubeStrategies/ShuffleCubeViaAPIStrategy.cs
Labels: Networking, WPF, Library / CLI

#71 Implemented ResetCubeViaSocketStrategy
  Solution/CubeProxy/Controllers/CubeController.cs
  Solution/DummyService/CubeInteractionHost.cs
  Solution/LibCubeIntegration/ResetCubeStrategies/ResetCubeViaSocketStrategy.cs
  Solution/LibCubeIntegration/Services/CubeServiceFacade.cs
  Solution/LibCubeIntegration/StrategyVendor.cs
Labels: Networking, Library / CLI
