Repository eeoooue/networked-cube, pull requests merged in 2025-03, with the labels that each got.

#16 created cube scrambling algorithm
  Solution/LibNetCube/CubeMoveOppositionGroups.cs
  Solution/LibNetCube/ScrambleAlgorithm.cs
  Solution/TestSuite/ScrambleAlgorithmTests.cs
Labels: Library / CLI

#15 Feature/implement parse move logic
  Solution/LibNetCube/CubeMoveMap.cs
  Solution/LibNetCube/MoveParser.cs
  Solution/TestSuite/MoveParserTests.cs
Labels: Library / CLI

#17 Housekeeping
  README.md
  Solution/CubeProxy/CubeProxy.csproj
  Solution/CubeProxy/Program.cs
  Solution/CubeProxy/PuzzleCubeServer.cs
  Solution/CubeProxy/PuzzleCubeWorker.cs
  Solution/CubeViewFacade/CubeViewFacade.csproj
  Solution/CubeViewFacade/CubeViewingHost.cs
  Solution/CubeViewFacade/Program.cs
  Solution/Solution.sln
  misc/netcube-system-design.png
Labels: documentation

#19 Fixed sub issue 12, created base API to issue spec
  Solution/CubeService/Controllers/CubeController.cs
  Solution/CubeService/CubeService.csproj
  Solution/CubeService/CubeService.http
  Solution/CubeService/Helper.cs
  Solution/CubeService/Program.cs
  Solution/CubeService/Properties/launchSettings.json
  Solution/CubeService/README.md
  Solution/CubeService/appsettings.Development.json
  Solution/CubeService/appsettings.json
  Solution/Solution.sln
Labels: Back End, Web API

#23 Implemented Cube Rotation
  Solution/DummyService/CubeInteractionHost.cs
  Solution/LibNetCube/CubePuzzle.cs
  Solution/LibNetCube/CubeState.cs
  Solution/LibNetCube/PuzzleRotation.cs
  Solution/TestSuite/ManipulationTests.cs
Labels: Library / CLI

#24 FaceViewerCLI now talks to CubeService
  Solution/FaceViewerCLI/GetCubeStrategies/GetCubeViaAPIStrategy.cs
  Solution/FaceViewerCLI/GetCubeStrategies/GetCubeViaSocketStrategy.cs
  Solution/FaceViewerCLI/GetCubeStrategies/IGetCubeStrategy.cs
  Solution/FaceViewerCLI/PerformMoveStrategies/IPerformMoveStrategy.cs
  Solution/FaceViewerCLI/PerformMoveStrategies/MoveViaAPIStrategy.cs
  Solution/FaceViewerCLI/PerformMoveStrategies/MoveViaSocketStrategy.cs
  Solution/FaceViewerCLI/Program.cs
Labels: Networking, Library / CLI

#27 Inject PuzzleCube as Singleton, not Scoped #25: done
  Solution/CubeService/Program.cs
Labels: Back End, Web API

#29 refactor: making LibCubeIntegration library async & refactoring
  Solution/FaceViewerCLI/Program.cs
  Solution/LibCubeIntegration/GetCubeStrategies/GetCubeViaAPIStrategy.cs
  Solution/LibCubeIntegration/GetCubeStrategies/GetCubeViaSocketStrategy.cs
  Solution/LibCubeIntegration/GetCubeStrategies/IGetCubeStrategy.cs
  Solution/LibCubeIntegration/PerformMoveStrategies/IPerformMoveStrategy.cs
  Solution/LibCubeIntegration/PerformMoveStrategies/MoveViaAPIStrategy.cs
  Solution/LibCubeIntegration/PerformMoveStrategies/MoveViaSocketStrategy.cs
Labels: Networking, Library / CLI

#35 Added a working version of CubeVisualizer Project
  Solution/CubeVisualizer/.config/dotnet-tools.json
  Solution/CubeVisualizer/Camera.cs
  Solution/CubeVisualizer/Content/3D Objects/Cube.fbx
  Solution/CubeVisualizer/Content/Content.mgcb
  Solution/CubeVisualizer/CubeGame.cs
  Solution/CubeVisualizer/CubeVisualizer.csproj
  Solution/CubeVisualizer/Icon.bmp
  Solution/CubeVisualizer/Icon.ico
  Solution/CubeVisualizer/Object3D.cs
  Solution/CubeVisualizer/Program.cs
  Solution/CubeVisualizer/RubiksCube.cs
  Solution/CubeVisualizer/app.manifest
  Solution/Solution.sln
Labels: Front End, MonoGame

#34 FaceViewer could use LibCubeIntegration to access CubeService #30:
  Solution/FaceViewer/App.xaml
  Solution/FaceViewer/App.xaml.cs
  Solution/FaceViewer/FaceViewer.csproj
  Solution/FaceViewer/MainWindow.xaml.cs
  Solution/FaceViewer/RelayCommand.cs
  Solution/FaceViewer/ViewModels/FaceViewModel.cs
  Solution/FaceViewer/ViewModels/MainViewModel.cs
  Solution/FaceViewer/Views/FaceView.xaml
  Solution/LibCubeIntegration/GetCubeStrategies/GetCubeViaSocketStrategy.cs
Labels: Networking, WPF

#36 Implemented networking to CubeVisualizer using the API closes #13
  Solution/CubeVisualizer/CubeGame.cs
  Solution/CubeVisualizer/CubeVisualizer.csproj
  Solution/CubeVisualizer/RubiksCube.cs
  Solution/Solution.sln
Labels: Front End, Networking, MonoGame

#38 Cube view facade could use lib cube integration to access cube service #33
  Solution/CubeViewFacade/CubeViewFacade.csproj
  Solution/CubeViewFacade/Program.cs
  Solution/FaceViewer/ViewModels/FaceViewModel.cs
Labels: Networking, Library / CLI

#37 refactor: using a cancellation Token for FaceViewModel
  Solution/FaceViewer/ViewModels/FaceViewModel.cs
Labels: Front End, Networking, WPF

#39 introducing a CubeService
  Solution/CubeViewFacade/Program.cs
  Solution/CubeVisualizer/CubeGame.cs
  Solution/FaceViewer/App.xaml.cs
  Solution/FaceViewer/ViewModels/FaceViewModel.cs
  Solution/FaceViewer/ViewModels/MainViewModel.cs
  Solution/FaceViewerCLI/Program.cs
  Solution/LibCubeIntegration/GetCubeStrategies/GetCubeViaAPIStrategy.cs
  Solution/LibCubeIntegration/GetCubeStrategies/GetCubeViaSocketStrategy.cs
  Solution/LibCubeIntegration/GetCubeStrategies/IGetCubeStrategy.cs
  Solution/LibCubeIntegration/PerformMoveStrategies/IPerformMoveStrategy.cs
  Solution/LibCubeIntegration/PerformMoveStrategies/MoveViaAPIStrategy.cs
  Solution/LibCubeIntegration/PerformMoveStrategies/MoveViaSocketStrategy.cs
  Solution/LibCubeIntegration/Services/CubeService.cs
Labels: Networking, Library / CLI

#42 Fix for CubeVisualizer face orientations
  Solution/CubeVisualizer/RubiksCube.cs
Labels: Front End, MonoGame

#43 Fix: API rejecting {move}' and {move}2
  Solution/CubeService/Controllers/CubeController.cs
  Solution/LibNetCube/CubePuzzle.cs
Labels: bug, Back End, Web API

#44 Renamed CubeService class to CubeServiceFacade
  Solution/CubeViewFacade/CubeViewingHost.cs
  Solution/CubeViewFacade/Program.cs
  Solution/CubeVisualizer/CubeGame.cs
  Solution/FaceViewer/App.xaml.cs
  Solution/FaceViewer/ViewModels/FaceViewModel.cs
  Solution/FaceViewer/ViewModels/MainViewModel.cs
  Solution/FaceViewerCLI/Program.cs
  Solution/LibCubeIntegration/Services/CubeServiceFacade.cs
Labels: Networking, Library / CLI

#49 Housekeeping
  Solution/LibNetCube/CubePuzzle.cs
  Solution/LibNetCube/MoveParser.cs
  misc/example-screenshot.png
Labels: enhancement, Library / CLI

#51 feat: added working reset functionality to reset the state of the cube
  Solution/CubeService/Controllers/CubeController.cs
  Solution/LibNetCube/CubePuzzle.cs
  Solution/TestSuite/CubePuzzleTests.cs
Labels: Library / CLI

#52 CubeManipulator MVVM Realisation
  Solution/CubeManipulator/CubeManipulator.csproj
  Solution/CubeManipulator/CubeManipulatorViewModel.cs
  Solution/CubeManipulator/MainWindow.xaml
  Solution/CubeManipulator/MainWindow.xaml.cs
  Solution/CubeManipulator/RelayCommand.cs
Labels: Front End, Networking, WPF
